name: Healthcheck pipeline

on:
  push:
    branches:
      - master

jobs:
  Healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ curl -s -o /dev/null -w "%{http_code}" https://full-stack-open-pokedex-eixg.onrender.com/healthh != 200 }}
      - name: Raise error
          core.error
