name: Healthcheck pipeline

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  Healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: basic healthcheck 
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://full-stack-open-pokedex-eixg.onrender.com/health
