name: Healthcheck pipeline

on:
  push:
    branches:
      - master

jobs:
  Healthcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ping application
        run: curl -s -o /dev/null -w "%{http_code}" https://full-stack-open-pokedex-eixg.onrender.com/health
